package com.fanni.expense_tracker.model;

public enum Category {
    HOUSING, TRANSPORTATION, FOOD, UTILITIES, HEALTHCARE,
    SAVING, HOUSEHOLD, PERSONAL, ENTERTAINMENT, MISCELLANEOUS,
    PETS, CLOTHES, SERVICES, UNCATEGORIZED,
    PAYMENT, ONETIME_INCOME
}
